import React from 'react';

const About = props => {
  return (
    <div>
      <h1>About</h1>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo, autem sed earum, accusantium iusto tenetur dicta libero odit quaerat quod eligendi! Officiis, modi architecto saepe beatae rem officia. Amet nobis earum distinctio omnis. Veritatis, iste, repudiandae corporis voluptas odit voluptatum dignissimos fugit ullam architecto quisquam blanditiis officia ab. Facilis, provident. Quam doloribus sunt molestiae, accusantium incidunt cum quibusdam? Beatae ipsa eum, assumenda omnis minus id distinctio maiores illum provident repudiandae cumque, officiis rerum molestiae nulla dolore quo ipsum similique in esse iure explicabo adipisci. Autem dignissimos aperiam iste temporibus magni, sit saepe quidem animi, veritatis obcaecati voluptates. Consectetur, obcaecati ex! Quae eaque autem animi, sunt qui eveniet officiis odit laudantium, unde ullam quod obcaecati explicabo nihil minus repellendus, reiciendis repellat dolorum expedita maiores veritatis hic dicta quidem velit. Magni ab ipsa et, eaque repellat sequi deleniti a temporibus adipisci iste omnis ipsum nemo quam incidunt possimus laboriosam nobis, sit enim sed sapiente est natus quas quos. Repellendus dicta cupiditate repudiandae architecto ex pariatur atque! Animi officia, fugit nihil culpa aliquid necessitatibus magnam incidunt vitae quisquam rem repellat impedit id omnis dolorem sit voluptatibus nobis aliquam delectus, facilis, cum minus? Nulla distinctio dolores doloremque eligendi amet ut provident accusamus, ullam eum ratione quod quibusdam, et, saepe sit voluptatem eius doloribus minus molestias assumenda sint deleniti mollitia odio nostrum? Provident voluptatum aut quibusdam corrupti nulla ea soluta, iure assumenda recusandae possimus id suscipit inventore esse excepturi quas itaque quae ducimus iste placeat, ipsum tempore hic culpa! Excepturi officiis expedita deleniti possimus quisquam harum inventore libero adipisci tempore alias. Nulla officia laborum maiores, iste voluptate qui tempore aut exercitationem ab minima sint optio ipsam veritatis molestias magni sunt dolorum dolor natus obcaecati cumque, ea vitae praesentium reprehenderit. Quia non soluta numquam facilis blanditiis quaerat voluptatibus corporis, facere culpa magnam laborum autem aliquid eum?
    </div>
  );
}

export default About;